import { COMMON_ERROR_STATUS_MAP } from '@orpc/server'

/**
 * HTTP status for each typed error `code`. oRPC carries no per-error status in
 * the contract, so a handler needs this map; any code missing here answers 500.
 */
export const ERROR_STATUS_MAP: Record<string, number> = {
  ...COMMON_ERROR_STATUS_MAP,
  INVALID_CREDENTIALS: 401,
  USER_NOT_FOUND: 404,
  ACCOUNT_LOCKED: 403,
  EMAIL_NOT_VERIFIED: 403,
  WEAK_PASSWORD: 422,
  SIGN_UP_DISABLED: 403,
  EMAIL_DOMAIN_NOT_ALLOWED: 403,
  EMAIL_TAKEN: 409,
  PHONE_TAKEN: 409,
  PROVIDER_NOT_CONFIGURED: 400,
  HUMAN_VERIFICATION_REQUIRED: 403,
  HUMAN_VERIFICATION_FAILED: 403,
  HUMAN_VERIFICATION_UNAVAILABLE: 503,
  INVALID_TOKEN: 401,
  TOKEN_REUSE_DETECTED: 401,
  SESSION_REVOKED: 401,
  MFA_REQUIRED: 401,
  INVALID_MFA_CODE: 422,
  FACTOR_NOT_FOUND: 404,
  FACTOR_ALREADY_VERIFIED: 409,
  STEP_UP_REQUIRED: 403,
  IMMUTABLE: 409,
  UNSUPPORTED_IMAGE_TYPE: 415,
  IMAGE_TOO_LARGE: 413,
  AVATAR_STORAGE_UNAVAILABLE: 503,
  IDENTITY_NOT_FOUND: 404,
  CANNOT_UNLINK_SOLE_CREDENTIAL: 409,
}
